### ISSUE TITLE
Cannot install vcf2fas/ problem with make

### ISSUE THREAD

**Issue by Kata-Pa** [brunonevado/vcf2fas#1]
Hello!
I followed the steps described on the website for installing the software in Linux, but when I run make, I get the following error:
g++ -Wall -O3 -std=c++11 -o vcf2fas source/main.cpp source/args.h source/args.cpp source/common.h source/common.cpp source/vcf.h source/vcf.cpp -lbpp-core -lbpp-seq -lbpp-phyl
source/main.cpp:14:78: fatal error: Bpp/Seq/Alphabet.all: No such file or directory
compilation terminated.
Makefile:18: recipe for target 'ROGRAM' failed
make: *** [ROGRAM] Error 1

I also installed bpp/seq, bpp/code and bpp/phyl with conda but I get the same error. Looking into the files of bpp seq I indeed cannot find the Alphabet.all file, instead there is a directory called just Alphabet. Any hint on what is wrong here?

Thank you,
/Katerina

**Comment by brunonevado** [comment]
Hi Katerina,

Maybe you installed bio++ on a non-standard location – possibly somewhere under conda ? If so, you will want to edit the Makefile, by uncommenting and adapting these lines:

# IDIR =/home/Bruno/local/include/bpp
# LDIR =/home/Bruno/local/lib/bpp/
# CFLAGS=-I$(IDIR) -L$(LDIR) -Wall -O3 -std=c++11
 

Make sure IDIR and LDIR point to wherever you installed bio++, and run the make command again.

Hopefully this works, but if not I also uploaded a statically-compiled vcf2fas (check under /bin), you can  try downloading and directly executing that file (no compiling needed, should work at least in some flavours of unix).

Let me know if this works for you.
Bruno

**Comment by Kata-Pa** [comment]
I used the compiled vcf2fas, worked, thank you!

**Comment by Kata-Pa** [comment]
However I get another error when I run it:
ERROR READING VCF FILE ##fileformat=VCFv4.2 : Unable to open infile vcf

I guess it has to do with my vcf files? Maybe some illegal character inside?

**Comment by brunonevado** [comment]
I don't think it is finding your vcf file at all – could you paste the command you used to run vcf2fas?

**Comment by Kata-Pa** [comment]
Aaaah I am so sorry, I just noticed it should be a text file with the path to the vcf file! Thanks again!
